included:
  - Project
  - Tuist
  - Workspace.swift

excluded:
  - .git
  - .githooks
  - Mulimi.xcworkspace
  - Project/**/Derived
  - Project/**/*.xcodeproj
  - Tuist/.build

only_rules:
  - closure_spacing
  - colon
  - comma
  - control_statement
  - empty_count
  - empty_parameters
  - first_where
  - force_cast
  - force_try
  - opening_brace
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - return_arrow_whitespace
  - statement_position
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - vertical_whitespace

reporter: "xcode"
